# Generated by Django 2.1.4 on 2018-12-24 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20181224_0235'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pontoturistico',
            options={'verbose_name_plural': 'Pontos Turísticos'},
        ),
    ]
