# Generated by Django 2.1.4 on 2018-12-24 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_pontoturistico_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pontoturistico',
            name='foto',
        ),
    ]
