# Generated by Django 2.1.4 on 2018-12-24 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atracao',
            options={'verbose_name_plural': 'atracoes'},
        ),
    ]
