# Generated by Django 2.1.4 on 2018-12-24 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0003_auto_20181223_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atracao',
            name='idade_minima',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
